In [1]:
import numpy as np

In [2]:
# array of vector
# v -> [[1,2,3,4],[4,5,6,7],[10.8,9.9,8.8]]

In [3]:
np.zeros?

In [5]:
vec = np.zeros((2,3))

In [6]:
vec

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
a = np.ones((3,9))

In [13]:
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [10]:
type(a)

numpy.ndarray

In [12]:
a.shape

(3, 9)

In [14]:
x = np.eye(5)

In [15]:
x

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [19]:
data1 = np.array([[1.2, 2.6, 3.99999], [4., 5., 6.], [7, 8, 9]], dtype = np.float64)
data1

array([[1.2    , 2.6    , 3.99999],
       [4.     , 5.     , 6.     ],
       [7.     , 8.     , 9.     ]])

In [21]:
li = data1.tolist()
li

[[1.2, 2.6, 3.99999], [4.0, 5.0, 6.0], [7.0, 8.0, 9.0]]

In [22]:
type(li)

list

In [25]:
data2 = np.array(li)
data2

array([[1.2    , 2.6    , 3.99999],
       [4.     , 5.     , 6.     ],
       [7.     , 8.     , 9.     ]])

In [26]:
np.random.normal(0, 1)

-0.9700498231222453

In [28]:
%%time
length = 10000000
res =[]
for i in range(length):
    res.append(np.random.normal(0, 1))


CPU times: user 14.5 s, sys: 113 ms, total: 14.6 s
Wall time: 14.6 s


In [29]:
%%time
np_list = np.random.normal(0, 1, length)

CPU times: user 278 ms, sys: 19.2 ms, total: 297 ms
Wall time: 296 ms


In [30]:
np_list[:10]

array([-0.16324406, -0.54389661, -1.19098423,  0.09771466,  1.83702789,
        0.28153768, -0.13398927,  0.35784641, -1.02265209, -0.99266457])

In [31]:
len(np_list)

10000000

In [32]:
len(res)

10000000

In [34]:
data16 = data1.astype(np.float16)

In [35]:
data16

array([[1.2, 2.6, 4. ],
       [4. , 5. , 6. ],
       [7. , 8. , 9. ]], dtype=float16)

In [36]:
type(data16)

numpy.ndarray

In [37]:
data16.shape

(3, 3)

In [38]:
data9 = data1.reshape(9,1)

In [39]:
data9

array([[1.2    ],
       [2.6    ],
       [3.99999],
       [4.     ],
       [5.     ],
       [6.     ],
       [7.     ],
       [8.     ],
       [9.     ]])

In [41]:
data91 = data1.reshape(1,9)

In [42]:
data91

array([[1.2    , 2.6    , 3.99999, 4.     , 5.     , 6.     , 7.     ,
        8.     , 9.     ]])

In [43]:
data1

array([[1.2    , 2.6    , 3.99999],
       [4.     , 5.     , 6.     ],
       [7.     , 8.     , 9.     ]])

In [46]:
data4 = data1+4
data4

array([[ 5.2    ,  6.6    ,  7.99999],
       [ 8.     ,  9.     , 10.     ],
       [11.     , 12.     , 13.     ]])

In [47]:
#Numpy has only array of vectors, 

In [50]:
data1[0]

array([1.2    , 2.6    , 3.99999])

In [51]:
data1[0][0]

1.2

In [52]:
data4-data1

array([[4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.]])

In [55]:
data3 = data1+data1[0]

In [56]:
data3

array([[ 2.4    ,  5.2    ,  7.99998],
       [ 5.2    ,  7.6    ,  9.99999],
       [ 8.2    , 10.6    , 12.99999]])

In [57]:
data3*4

array([[ 9.6    , 20.8    , 31.99992],
       [20.8    , 30.4    , 39.99996],
       [32.8    , 42.4    , 51.99996]])

In [58]:
data3 * np.eye(3)

array([[ 2.4    ,  0.     ,  0.     ],
       [ 0.     ,  7.6    ,  0.     ],
       [ 0.     ,  0.     , 12.99999]])

In [59]:
data3* data1

array([[  2.88   ,  13.52   ,  31.99984],
       [ 20.8    ,  38.     ,  59.99994],
       [ 57.4    ,  84.8    , 116.99991]])

In [61]:
data1** 0.5

array([[1.09544512, 1.61245155, 1.9999975 ],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [62]:
np.sqrt(data1)

array([[1.09544512, 1.61245155, 1.9999975 ],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [63]:
data1

array([[1.2    , 2.6    , 3.99999],
       [4.     , 5.     , 6.     ],
       [7.     , 8.     , 9.     ]])

In [64]:
data1 / 3

array([[0.4       , 0.86666667, 1.33333   ],
       [1.33333333, 1.66666667, 2.        ],
       [2.33333333, 2.66666667, 3.        ]])

In [65]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [69]:
np.ones((5,3))*5

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [73]:
x = np.arange(9.0)

In [74]:
x

array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [76]:
sp = np.split(x,3)

In [77]:
sp

[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7., 8.])]

In [79]:
sp[0].tolist()

[0.0, 1.0, 2.0]

In [81]:
x.shape

(9,)

In [83]:
y = x.reshape(3,3)

In [84]:
y

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [85]:
y[1:]

array([[3., 4., 5.],
       [6., 7., 8.]])

In [86]:
y[:2, :2]

array([[0., 1.],
       [3., 4.]])

In [87]:
y[0:]

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [88]:
y[2:]

array([[6., 7., 8.]])

In [89]:
y[-1:]

array([[6., 7., 8.]])

In [90]:
y[-2:]

array([[3., 4., 5.],
       [6., 7., 8.]])

In [91]:
y[:-1]

array([[0., 1., 2.],
       [3., 4., 5.]])

In [93]:
y[1:, 1:]

array([[4., 5.],
       [7., 8.]])

In [94]:
y[1:, 0:]

array([[3., 4., 5.],
       [6., 7., 8.]])

In [95]:
y[1:, 1:] = [[9,9], [9,9]]

In [96]:
y

array([[0., 1., 2.],
       [3., 9., 9.],
       [6., 9., 9.]])

In [98]:
y[1:, 1:] = [[4,5], [7,8]]

In [99]:
y

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [101]:
y[:2, :2]

array([[0., 1.],
       [3., 4.]])